import type { Product } from "@/types"

// Initial products data
const initialProducts: Product[] = [
  {
    id: 1,
    name: "RGB Gaming Keyboard Pro",
    price: 149.99,
    category: "Peripherals",
    stock: 35,
    description: "Mechanical RGB gaming keyboard with 50 million keystrokes durability",
    image: "/products/rgb-gaming-keyboard.jpg",
    createdAt: "2024-01-15",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 2,
    name: "Ultra HD Gaming Mouse",
    price: 79.99,
    category: "Peripherals",
    stock: 52,
    description: "16000 DPI precision gaming mouse with customizable RGB lighting",
    image: "/products/gaming-mouse.jpg",
    createdAt: "2024-01-14",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 3,
    name: "4K Gaming Monitor 144Hz",
    price: 499.99,
    category: "Displays",
    stock: 18,
    description: "4K UHD 27-inch gaming monitor with 144Hz refresh rate and HDR",
    image: "/products/gaming-monitor.jpg",
    createdAt: "2024-01-13",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 4,
    name: "RTX 4090 Graphics Card",
    price: 1599.99,
    category: "Components",
    stock: 8,
    description: "Flagship NVIDIA RTX 4090 for ultimate gaming performance",
    image: "/products/graphics-card.jpg",
    createdAt: "2024-01-12",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 5,
    name: "Gaming Headset Pro",
    price: 199.99,
    category: "Audio",
    stock: 42,
    description: "7.1 Surround sound gaming headset with noise cancellation",
    image: "/products/gaming-headset.jpg",
    createdAt: "2024-01-11",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 6,
    name: "Gaming Chair Ergonomic",
    price: 449.99,
    category: "Furniture",
    stock: 25,
    description: "Premium ergonomic gaming chair with lumbar support",
    image: "/products/gaming-chair.jpg",
    createdAt: "2024-01-10",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 7,
    name: "1TB NVMe SSD Gaming",
    price: 89.99,
    category: "Storage",
    stock: 60,
    description: "High-speed NVMe SSD for fast game loading",
    image: "/products/nvme-ssd.jpg",
    createdAt: "2024-01-09",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 8,
    name: "Gaming Mousepad XL",
    price: 49.99,
    category: "Accessories",
    stock: 88,
    description: "Extended RGB gaming mousepad with wireless charging",
    image: "/products/mousepad.jpg",
    createdAt: "2024-01-08",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 9,
    name: "144Hz 1440p Monitor",
    price: 349.99,
    category: "Displays",
    stock: 22,
    description: "27-inch 1440p 144Hz gaming monitor for competitive play",
    image: "/products/144hz-monitor.jpg",
    createdAt: "2024-01-07",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 10,
    name: "Mechanical Switch Tester",
    price: 29.99,
    category: "Accessories",
    stock: 100,
    description: "Test 6 different mechanical switch types for your keyboard",
    image: "/products/switch-tester.jpg",
    createdAt: "2024-01-06",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 11,
    name: "RGB Controller Hub",
    price: 39.99,
    category: "Accessories",
    stock: 45,
    description: "Control all your RGB devices from one central hub",
    image: "/placeholder.svg",
    createdAt: "2024-01-05",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 12,
    name: "Gaming PC Case",
    price: 129.99,
    category: "Components",
    stock: 30,
    description: "Tempered glass gaming PC case with RGB fans included",
    image: "/placeholder.svg",
    createdAt: "2024-01-04",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 13,
    name: "Pro Webcam 1080p",
    price: 99.99,
    category: "Streaming",
    stock: 35,
    description: "1080p 60fps webcam for streaming and content creation",
    image: "/placeholder.svg",
    createdAt: "2024-01-03",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 14,
    name: "USB Hub 3.2 Gen 2",
    price: 49.99,
    category: "Accessories",
    stock: 67,
    description: "7-port USB 3.2 Gen 2 hub with fast data transfer",
    image: "/placeholder.svg",
    createdAt: "2024-01-02",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 15,
    name: "Gaming Desk RGB",
    price: 299.99,
    category: "Furniture",
    stock: 15,
    description: "Large gaming desk with built-in RGB lighting",
    image: "/placeholder.svg",
    createdAt: "2024-01-01",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 16,
    name: "Mechanical Keyboard Switches",
    price: 59.99,
    category: "Components",
    stock: 80,
    description: "110-pack custom mechanical switches for gaming keyboards",
    image: "/placeholder.svg",
    createdAt: "2023-12-31",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 17,
    name: "Cooling Pad Gaming Laptop",
    price: 49.99,
    category: "Accessories",
    stock: 55,
    description: "Laptop cooling pad with 5 fans for gaming sessions",
    image: "/placeholder.svg",
    createdAt: "2023-12-30",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 18,
    name: "RGB Memory Kit 32GB",
    price: 159.99,
    category: "Components",
    stock: 28,
    description: "32GB RGB RAM for high-performance gaming rigs",
    image: "/placeholder.svg",
    createdAt: "2023-12-29",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 19,
    name: "Microphone Studio Gaming",
    price: 129.99,
    category: "Streaming",
    stock: 40,
    description: "Professional USB microphone for streaming with pop filter",
    image: "/placeholder.svg",
    createdAt: "2023-12-28",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 20,
    name: "Display Port Cable 2.1",
    price: 24.99,
    category: "Cables",
    stock: 120,
    description: "8K-ready DisplayPort 2.1 cable for gaming monitors",
    image: "/placeholder.svg",
    createdAt: "2023-12-27",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 21,
    name: "RGB Fan Kit 6-Pack",
    price: 79.99,
    category: "Cooling",
    stock: 38,
    description: "6 RGB case fans with synchronized lighting control",
    image: "/placeholder.svg",
    createdAt: "2023-12-26",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 22,
    name: "CPU Cooler Tower RGB",
    price: 89.99,
    category: "Cooling",
    stock: 32,
    description: "High-performance CPU cooler with RGB lighting",
    image: "/placeholder.svg",
    createdAt: "2023-12-25",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 23,
    name: "Power Supply 850W Gold",
    price: 159.99,
    category: "Components",
    stock: 25,
    description: "850W 80+ Gold certified power supply for gaming PC",
    image: "/placeholder.svg",
    createdAt: "2023-12-24",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 24,
    name: "Motherboard Gaming Pro",
    price: 249.99,
    category: "Components",
    stock: 20,
    description: "Premium gaming motherboard with WiFi 6E and RGB",
    image: "/placeholder.svg",
    createdAt: "2023-12-23",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 25,
    name: "Streaming Light Kit",
    price: 99.99,
    category: "Streaming",
    stock: 33,
    description: "RGB LED panel lighting kit for professional streaming setup",
    image: "/placeholder.svg",
    createdAt: "2023-12-22",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 26,
    name: "Game Controller Pro",
    price: 69.99,
    category: "Peripherals",
    stock: 48,
    description: "Premium wireless gaming controller with customizable buttons",
    image: "/placeholder.svg",
    createdAt: "2023-12-21",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 27,
    name: "Desk Mount Monitor Arm",
    price: 79.99,
    category: "Accessories",
    stock: 44,
    description: "Dual monitor arm mount with full articulation",
    image: "/placeholder.svg",
    createdAt: "2023-12-20",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 28,
    name: "Gaming Laptop Stand",
    price: 39.99,
    category: "Accessories",
    stock: 70,
    description: "Adjustable laptop stand for ergonomic gaming",
    image: "/placeholder.svg",
    createdAt: "2023-12-19",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 29,
    name: "Mechanical Keyboard TKL",
    price: 129.99,
    category: "Peripherals",
    stock: 41,
    description: "Tenkeyless mechanical gaming keyboard with RGB",
    image: "/placeholder.svg",
    createdAt: "2023-12-18",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 30,
    name: "Mouse Bungee Cable",
    price: 19.99,
    category: "Accessories",
    stock: 95,
    description: "Cable management system for gaming mouse",
    image: "/placeholder.svg",
    createdAt: "2023-12-17",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 31,
    name: "Gaming Backpack RGB",
    price: 89.99,
    category: "Accessories",
    stock: 28,
    description: "Backpack for transporting gaming gear with RGB accent",
    image: "/placeholder.svg",
    createdAt: "2023-12-16",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 32,
    name: "Capture Card 4K",
    price: 179.99,
    category: "Streaming",
    stock: 19,
    description: "4K capable capture card for console and PC streaming",
    image: "/placeholder.svg",
    createdAt: "2023-12-15",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 33,
    name: "Gaming Phone Stand",
    price: 29.99,
    category: "Accessories",
    stock: 65,
    description: "Rotating phone stand for mobile gaming",
    image: "/placeholder.svg",
    createdAt: "2023-12-14",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 34,
    name: "Wireless Charger Fast",
    price: 49.99,
    category: "Accessories",
    stock: 52,
    description: "15W fast wireless charging pad for gaming devices",
    image: "/placeholder.svg",
    createdAt: "2023-12-13",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 35,
    name: "USB-C Hub Gaming",
    price: 59.99,
    category: "Accessories",
    stock: 43,
    description: "Portable USB-C hub with multiple ports for gaming setup",
    image: "/placeholder.svg",
    createdAt: "2023-12-12",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 36,
    name: "RGB Light Strip 5m",
    price: 39.99,
    category: "Lighting",
    stock: 72,
    description: "5-meter smart RGB LED strip for room setup",
    image: "/placeholder.svg",
    createdAt: "2023-12-11",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 37,
    name: "Gaming Water Cooler",
    price: 299.99,
    category: "Cooling",
    stock: 12,
    description: "360mm liquid cooling system for gaming PC",
    image: "/placeholder.svg",
    createdAt: "2023-12-10",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 38,
    name: "Keyboard Stabilizers",
    price: 29.99,
    category: "Components",
    stock: 85,
    description: "Mechanical keyboard stabilizers for custom builds",
    image: "/placeholder.svg",
    createdAt: "2023-12-09",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 39,
    name: "Mouse Feet Replacement",
    price: 14.99,
    category: "Accessories",
    stock: 110,
    description: "PTFE mouse feet replacement pads for smooth gliding",
    image: "/placeholder.svg",
    createdAt: "2023-12-08",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 40,
    name: "Desk Lamp RGB Gaming",
    price: 69.99,
    category: "Lighting",
    stock: 36,
    description: "Smart RGB desk lamp with adjustable brightness",
    image: "/placeholder.svg",
    createdAt: "2023-12-07",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 41,
    name: "Gaming Ext Cable 25ft",
    price: 34.99,
    category: "Cables",
    stock: 58,
    description: "Extended gaming headset cable 25 feet",
    image: "/placeholder.svg",
    createdAt: "2023-12-06",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 42,
    name: "Mechanical Keyboard 75%",
    price: 159.99,
    category: "Peripherals",
    stock: 34,
    description: "75% form factor mechanical gaming keyboard",
    image: "/placeholder.svg",
    createdAt: "2023-12-05",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 43,
    name: "Gaming Mouse Grip",
    price: 19.99,
    category: "Accessories",
    stock: 89,
    description: "Replaceable grip tape for gaming mouse",
    image: "/placeholder.svg",
    createdAt: "2023-12-04",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 44,
    name: "RGB Keyboard Keycaps",
    price: 79.99,
    category: "Components",
    stock: 47,
    description: "Premium PBT RGB backlit keycap set",
    image: "/placeholder.svg",
    createdAt: "2023-12-03",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 45,
    name: "Gaming Monitor Arm",
    price: 99.99,
    category: "Accessories",
    stock: 29,
    description: "Full motion monitor arm for gaming displays",
    image: "/placeholder.svg",
    createdAt: "2023-12-02",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 46,
    name: "SSD Enclosure USB-C",
    price: 34.99,
    category: "Storage",
    stock: 63,
    description: "External SSD enclosure with USB-C 3.2 Gen 2",
    image: "/placeholder.svg",
    createdAt: "2023-12-01",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 47,
    name: "Gaming Desk Pad",
    price: 79.99,
    category: "Accessories",
    stock: 39,
    description: "Large RGB gaming desk mat with wireless charging",
    image: "/placeholder.svg",
    createdAt: "2023-11-30",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 48,
    name: "Cable Organizer Kit",
    price: 24.99,
    category: "Accessories",
    stock: 98,
    description: "Cable management kit for gaming setup",
    image: "/placeholder.svg",
    createdAt: "2023-11-29",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 49,
    name: "Gaming Soundbar",
    price: 199.99,
    category: "Audio",
    stock: 22,
    description: "2.1 RGB soundbar with subwoofer for gaming",
    image: "/placeholder.svg",
    createdAt: "2023-11-28",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
  {
    id: 50,
    name: "Ultimate Gaming Bundle",
    price: 299.99,
    category: "Bundles",
    stock: 10,
    description: "Complete gaming starter pack with keyboard, mouse, mousepad",
    image: "/placeholder.svg",
    createdAt: "2023-11-27",
    sellerId: "2",
    sellerName: "Gaming Seller",
  },
]

let nextId = 51
let products = [...initialProducts]

export function getProducts(): Product[] {
  return products
}

export function updateProducts(newProducts: Product[]): void {
  products = newProducts
}

export function addProduct(product: Omit<Product, "id">): Product {
  const newProduct: Product = {
    ...product,
    id: nextId++,
    createdAt: new Date().toISOString().split("T")[0],
    image: product.image || "/placeholder.svg",
  }
  products.push(newProduct)
  console.log("[v0] Product added with ID:", newProduct.id)
  return newProduct
}

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id)
}

export function updateProduct(id: number, updates: Partial<Product>): Product | undefined {
  const index = products.findIndex((p) => p.id === id)
  if (index === -1) return undefined

  products[index] = { ...products[index], ...updates }
  console.log("[v0] Product updated:", products[index])
  return products[index]
}

export function deleteProduct(id: number): boolean {
  const index = products.findIndex((p) => p.id === id)
  if (index === -1) return false

  products.splice(index, 1)
  console.log("[v0] Product deleted with ID:", id)
  return true
}
