import type { Product } from "@/types"

export const sampleProducts: Product[] = [
  {
    id: 1,
    name: "Elite Gaming Mouse Pro",
    category: "Peripherals",
    price: 79.99,
    image: "/products/gaming-mouse.jpg",
    description: "Ultra-precise sensor with 20,000 DPI. Perfect for competitive gaming.",
    stock: 15,
    sellerId: "seller1",
    sellerName: "ProGear Store",
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Mechanical Gaming Keyboard RGB",
    category: "Peripherals",
    price: 149.99,
    image: "/products/mechanical-keyboard.jpg",
    description: "Cherry MX switches with per-key RGB lighting. Customizable macros.",
    stock: 12,
    sellerId: "seller1",
    sellerName: "ProGear Store",
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Surround Sound Gaming Headset",
    category: "Audio",
    price: 119.99,
    image: "/products/gaming-headset.jpg",
    description: "7.1 surround sound with noise-canceling mic. Premium comfort padding.",
    stock: 20,
    sellerId: "seller2",
    sellerName: "AudioMax Gaming",
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "4K Gaming Monitor 144Hz",
    category: "Displays",
    price: 399.99,
    image: "/products/gaming-monitor.jpg",
    description: "Curved 27-inch display. 144Hz refresh rate. HDR support.",
    stock: 8,
    sellerId: "seller2",
    sellerName: "AudioMax Gaming",
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "RTX 4080 Graphics Card",
    category: "Components",
    price: 1199.99,
    image: "/products/gpu-graphics-card.jpg",
    description: "High-end GPU for 4K gaming. 16GB GDDR6X memory.",
    stock: 5,
    sellerId: "seller3",
    sellerName: "TechHub Components",
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Extended Gaming Mousepad",
    category: "Peripherals",
    price: 34.99,
    image: "/products/gaming-mousepad.jpg",
    description: "Large surface area. Non-slip base. Precision tracking surface.",
    stock: 25,
    sellerId: "seller1",
    sellerName: "ProGear Store",
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Pro Gaming Chair",
    category: "Furniture",
    price: 249.99,
    image: "/products/gaming-chair.jpg",
    description: "Ergonomic design with lumbar support. Premium materials.",
    stock: 10,
    sellerId: "seller3",
    sellerName: "TechHub Components",
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Wireless Gaming Controller",
    category: "Peripherals",
    price: 69.99,
    image: "/products/controller-gamepad.jpg",
    description: "2.4GHz wireless connection. 20-hour battery life.",
    stock: 18,
    sellerId: "seller2",
    sellerName: "AudioMax Gaming",
    createdAt: new Date().toISOString(),
  },
]
